### ISSUE TITLE
Malformed sizes attribute value for blog post images

### ISSUE THREAD

**Issue by sdennett55** [Pustelto/personal_web#31]
Hello!

Just read your [Optimizing CSS for faster page loads](https://pustelto.com/blog/optimizing-css-for-faster-page-loads/) article, great read! As someone also curious about frontend performance, I decided to check how you were using responsive images and noticed that for your blog post images the sizes attribute is set as as: `sizes="100vw, (min-width: 39.5rem) 608px"`.

The order of the media queries matter, and the first one that "matches" is selected. So the browser goes, oh the display size is `100vw`, you got it! Therefore, users are requesting the largest (1800px) file in some cases (my browser window maximized on my display is 1905px wide, so the browser assumes the display size of the image is 1905px).

Just reverse the order `sizes="(min-width: 39.5rem) 608px, 100vw"` and I think you'll shave off some KBs. I was going to fork and make the one line contribution, but I haven't used eleventy before and so I'm not sure how to build and test.

**Comment by Pustelto** [comment]
🤦 Oh my...

Thanks for pointing this out. You are absolutely correct about the wrong format. Only last value can be without a media query. Will fix that asap.
